# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '16.x'
  displayName: 'Install Node.js'

- script: |
    npm install
    #npm run start
  displayName: 'npm install and build'

- publish: $(System.DefaultWorkingDirectory)/node
  artifact: WebApp

- task: AzureRmWebAppDeployment@4
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'Visual Studio Enterprise Subscription – MPN (36c7de9d-d66a-4965-8013-b052bff6bfb1)'
    appType: 'webAppLinux'
    WebAppName: 'nodeapp9'
    packageForLinux: '$(System.DefaultWorkingDirectory)/node'
    RuntimeStack: 'NODE|10.14'
    StartupCommand: 'npm run start'